import { Product } from "@/types/product";

// AUTO-GENERATED by scripts/generate-shop-data.mjs. Prices are per-category (AED).
const shopData: Product[] = [
  {
    title: "Dress Long Robe Abaya",
    reviews: 12,
    price: 1000,
    discountedPrice: 1000,
    id: 1,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-dress-long-robe-abaya-1.avif",
      ],
      previews: [
        "/images/products/gsp-dress-long-robe-abaya-1.avif",
      ],
    },
  },
  {
    title: "Jancoco Popular Knitted Sweater Set Loose Women",
    reviews: 19,
    price: 4000,
    discountedPrice: 4000,
    id: 2,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-jancoco-popular-knitted-sweater-set-loose-women-1.jpg",
      ],
      previews: [
        "/images/products/gsp-jancoco-popular-knitted-sweater-set-loose-women-1.jpg",
      ],
    },
  },
  {
    title: "Japanese Style Luxury Cashmere And Wool Fabric",
    reviews: 26,
    price: 6000,
    discountedPrice: 6000,
    id: 3,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-japanese-style-luxury-cashmere-and-wool-fabric-1.jpg",
      ],
      previews: [
        "/images/products/gsp-japanese-style-luxury-cashmere-and-wool-fabric-1.jpg",
      ],
    },
  },
  {
    title: "Long Shawl Wrap Scarf",
    reviews: 8,
    price: 6000,
    discountedPrice: 6000,
    id: 4,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-long-shawl-wrap-scarf-1.jpg",
      ],
      previews: [
        "/images/products/gsp-long-shawl-wrap-scarf-1.jpg",
      ],
    },
  },
  {
    title: "Loose Outfits Spring Summer Streetwear Long Sleeve",
    reviews: 15,
    price: 4000,
    discountedPrice: 4000,
    id: 5,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-loose-outfits-spring-summer-streetwear-long-slee-1.jpg",
        "/images/products/gsp-loose-outfits-spring-summer-streetwear-long-slee-2.jpg",
        "/images/products/gsp-loose-outfits-spring-summer-streetwear-long-slee-3.avif",
      ],
      previews: [
        "/images/products/gsp-loose-outfits-spring-summer-streetwear-long-slee-1.jpg",
        "/images/products/gsp-loose-outfits-spring-summer-streetwear-long-slee-2.jpg",
        "/images/products/gsp-loose-outfits-spring-summer-streetwear-long-slee-3.avif",
      ],
    },
  },
  {
    title: "Polyester Scarf",
    reviews: 22,
    price: 6000,
    discountedPrice: 6000,
    id: 6,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-polyester-scarf-1.jpg",
      ],
      previews: [
        "/images/products/gsp-polyester-scarf-1.jpg",
      ],
    },
  },
  {
    title: "Sleeveless V-Neck Maxi Elegant Tiered Ruffle Stripe Casual Daily Dress",
    reviews: 29,
    price: 1000,
    discountedPrice: 1000,
    id: 7,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-sleeveless-v-neck-maxi-elegant-tiered-ruffle-str-1.png",
      ],
      previews: [
        "/images/products/gsp-sleeveless-v-neck-maxi-elegant-tiered-ruffle-str-1.png",
      ],
    },
  },
  {
    title: "Short Scarf For Women",
    reviews: 11,
    price: 6000,
    discountedPrice: 6000,
    id: 8,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-short-scarf-for-women-1.jpg",
      ],
      previews: [
        "/images/products/gsp-short-scarf-for-women-1.jpg",
      ],
    },
  },
  {
    title: "Scarf",
    reviews: 18,
    price: 6000,
    discountedPrice: 6000,
    id: 9,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-scarf-1.png",
      ],
      previews: [
        "/images/products/gsp-scarf-1.png",
      ],
    },
  },
  {
    title: "2026 Sexy Women's Bikini,",
    reviews: 25,
    price: 1500,
    discountedPrice: 1500,
    id: 10,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-2026-sexy-women-s-bikini-1.avif",
      ],
      previews: [
        "/images/products/gsp-2026-sexy-women-s-bikini-1.avif",
      ],
    },
  },
  {
    title: "A-line Evening Dress",
    reviews: 7,
    price: 1000,
    discountedPrice: 1000,
    id: 11,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-a-line-evening-dress-1.avif",
      ],
      previews: [
        "/images/products/gsp-a-line-evening-dress-1.avif",
      ],
    },
  },
  {
    title: "Arabic Evening Dress",
    reviews: 14,
    price: 1000,
    discountedPrice: 1000,
    id: 12,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-arabic-evening-dress-1.avif",
      ],
      previews: [
        "/images/products/gsp-arabic-evening-dress-1.avif",
      ],
    },
  },
  {
    title: "Befree Summer Long Vintage",
    reviews: 21,
    price: 4000,
    discountedPrice: 4000,
    id: 13,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-befree-summer-long-vintage-1.avif",
      ],
      previews: [
        "/images/products/gsp-befree-summer-long-vintage-1.avif",
      ],
    },
  },
  {
    title: "Beige Solid Blouse",
    reviews: 28,
    price: 4000,
    discountedPrice: 4000,
    id: 14,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-beige-solid-blouse-1.avif",
        "/images/products/gsp-beige-solid-blouse-2.avif",
      ],
      previews: [
        "/images/products/gsp-beige-solid-blouse-1.avif",
        "/images/products/gsp-beige-solid-blouse-2.avif",
      ],
    },
  },
  {
    title: "Blue Half Slives",
    reviews: 10,
    price: 4000,
    discountedPrice: 4000,
    id: 15,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-blue-half-slives-1.avif",
      ],
      previews: [
        "/images/products/gsp-blue-half-slives-1.avif",
      ],
    },
  },
  {
    title: "Classic Printed Dresses",
    reviews: 17,
    price: 1000,
    discountedPrice: 1000,
    id: 16,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-classic-printed-dresses-1.avif",
      ],
      previews: [
        "/images/products/gsp-classic-printed-dresses-1.avif",
      ],
    },
  },
  {
    title: "Elegant Women's Satin",
    reviews: 24,
    price: 4000,
    discountedPrice: 4000,
    id: 17,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-elegant-women-s-satin-1.avif",
      ],
      previews: [
        "/images/products/gsp-elegant-women-s-satin-1.avif",
      ],
    },
  },
  {
    title: "Floral Print Swimsuit With Padded Bra And Brazilian Bottom",
    reviews: 6,
    price: 1500,
    discountedPrice: 1500,
    id: 18,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-floral-print-swimsuit-with-padded-bra-and-brazil-1.avif",
      ],
      previews: [
        "/images/products/gsp-floral-print-swimsuit-with-padded-bra-and-brazil-1.avif",
      ],
    },
  },
  {
    title: "Gold Prom Dress",
    reviews: 13,
    price: 1000,
    discountedPrice: 1000,
    id: 19,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-gold-prom-dress-1.avif",
      ],
      previews: [
        "/images/products/gsp-gold-prom-dress-1.avif",
      ],
    },
  },
  {
    title: "Islamic Jalabiya, Turkish Kaftan",
    reviews: 20,
    price: 1000,
    discountedPrice: 1000,
    id: 20,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-islamic-jalabiya-turkish-kaftan-1.avif",
      ],
      previews: [
        "/images/products/gsp-islamic-jalabiya-turkish-kaftan-1.avif",
      ],
    },
  },
  {
    title: "Long Evening Dress",
    reviews: 27,
    price: 1000,
    discountedPrice: 1000,
    id: 21,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-long-evening-dress-1.avif",
      ],
      previews: [
        "/images/products/gsp-long-evening-dress-1.avif",
      ],
    },
  },
  {
    title: "Luxefay",
    reviews: 9,
    price: 4000,
    discountedPrice: 4000,
    id: 22,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-luxefay-1.avif",
      ],
      previews: [
        "/images/products/gsp-luxefay-1.avif",
      ],
    },
  },
  {
    title: "Luxurious A-line Evening Dress",
    reviews: 16,
    price: 1000,
    discountedPrice: 1000,
    id: 23,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-luxurious-a-line-evening-dress-1.avif",
      ],
      previews: [
        "/images/products/gsp-luxurious-a-line-evening-dress-1.avif",
      ],
    },
  },
  {
    title: "Luxurious",
    reviews: 23,
    price: 4000,
    discountedPrice: 4000,
    id: 24,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-luxurious-1.avif",
      ],
      previews: [
        "/images/products/gsp-luxurious-1.avif",
      ],
    },
  },
  {
    title: "Luxury Prom Dress",
    reviews: 5,
    price: 1000,
    discountedPrice: 1000,
    id: 25,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-luxury-prom-dress-1.avif",
      ],
      previews: [
        "/images/products/gsp-luxury-prom-dress-1.avif",
      ],
    },
  },
  {
    title: "Mirage's Luxurious Mermaid",
    reviews: 12,
    price: 1000,
    discountedPrice: 1000,
    id: 26,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-mirage-s-luxurious-mermaid-1.avif",
      ],
      previews: [
        "/images/products/gsp-mirage-s-luxurious-mermaid-1.avif",
      ],
    },
  },
  {
    title: "Moroccan Arabic Kaftan",
    reviews: 19,
    price: 1000,
    discountedPrice: 1000,
    id: 27,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-moroccan-arabic-kaftan-1.avif",
      ],
      previews: [
        "/images/products/gsp-moroccan-arabic-kaftan-1.avif",
      ],
    },
  },
  {
    title: "Evening Dress",
    reviews: 26,
    price: 1000,
    discountedPrice: 1000,
    id: 28,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-new-2026-amanda-mermaid-1.avif",
      ],
      previews: [
        "/images/products/gsp-new-2026-amanda-mermaid-1.avif",
      ],
    },
  },
  {
    title: "Nibber Women's Prom Dress",
    reviews: 8,
    price: 1000,
    discountedPrice: 1000,
    id: 29,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-nibber-women-s-prom-dress-1.avif",
        "/images/products/gsp-nibber-women-s-prom-dress-2.avif",
      ],
      previews: [
        "/images/products/gsp-nibber-women-s-prom-dress-1.avif",
        "/images/products/gsp-nibber-women-s-prom-dress-2.avif",
      ],
    },
  },
  {
    title: "Party Dress",
    reviews: 15,
    price: 1000,
    discountedPrice: 1000,
    id: 30,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-party-dress-1.avif",
      ],
      previews: [
        "/images/products/gsp-party-dress-1.avif",
      ],
    },
  },
  {
    title: "Roses Sequined",
    reviews: 22,
    price: 4000,
    discountedPrice: 4000,
    id: 31,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-roses-sequined-1.avif",
      ],
      previews: [
        "/images/products/gsp-roses-sequined-1.avif",
      ],
    },
  },
  {
    title: "Roseinthebox Strapless",
    reviews: 29,
    price: 4000,
    discountedPrice: 4000,
    id: 32,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-roseinthebox-strapless-1.avif",
      ],
      previews: [
        "/images/products/gsp-roseinthebox-strapless-1.avif",
      ],
    },
  },
  {
    title: "Swimwear Set",
    reviews: 11,
    price: 1500,
    discountedPrice: 1500,
    id: 33,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-sexy-bandeau-bikini-set-2026-1.avif",
        "/images/products/gsp-sexy-bandeau-bikini-set-2026-2.avif",
        "/images/products/gsp-sexy-bandeau-bikini-set-2026-3.avif",
      ],
      previews: [
        "/images/products/gsp-sexy-bandeau-bikini-set-2026-1.avif",
        "/images/products/gsp-sexy-bandeau-bikini-set-2026-2.avif",
        "/images/products/gsp-sexy-bandeau-bikini-set-2026-3.avif",
      ],
    },
  },
  {
    title: "Sexy Brazilian Bikini Set",
    reviews: 18,
    price: 1500,
    discountedPrice: 1500,
    id: 34,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-sexy-brazilian-bikini-set-1.avif",
        "/images/products/gsp-sexy-brazilian-bikini-set-2.avif",
      ],
      previews: [
        "/images/products/gsp-sexy-brazilian-bikini-set-1.avif",
        "/images/products/gsp-sexy-brazilian-bikini-set-2.avif",
      ],
    },
  },
  {
    title: "Sexy Triangle Swimsuit For Women",
    reviews: 25,
    price: 1500,
    discountedPrice: 1500,
    id: 35,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-sexy-triangle-swimsuit-for-women-1.avif",
        "/images/products/gsp-sexy-triangle-swimsuit-for-women-2.avif",
      ],
      previews: [
        "/images/products/gsp-sexy-triangle-swimsuit-for-women-1.avif",
        "/images/products/gsp-sexy-triangle-swimsuit-for-women-2.avif",
      ],
    },
  },
  {
    title: "Sexy Strapless Short",
    reviews: 7,
    price: 4000,
    discountedPrice: 4000,
    id: 36,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-sexy-strapless-short-1.avif",
      ],
      previews: [
        "/images/products/gsp-sexy-strapless-short-1.avif",
      ],
    },
  },
  {
    title: "Sexy Women's Triangle Halter Bikini",
    reviews: 14,
    price: 1500,
    discountedPrice: 1500,
    id: 37,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-sexy-women-s-triangle-halter-bikini-1.avif",
        "/images/products/gsp-sexy-women-s-triangle-halter-bikini-2.avif",
      ],
      previews: [
        "/images/products/gsp-sexy-women-s-triangle-halter-bikini-1.avif",
        "/images/products/gsp-sexy-women-s-triangle-halter-bikini-2.avif",
      ],
    },
  },
  {
    title: "Sky Blue Starfish Embellished Thong",
    reviews: 21,
    price: 1500,
    discountedPrice: 1500,
    id: 38,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-sky-blue-starfish-embellished-thong-1.avif",
      ],
      previews: [
        "/images/products/gsp-sky-blue-starfish-embellished-thong-1.avif",
      ],
    },
  },
  {
    title: "Women Half Slives",
    reviews: 28,
    price: 4000,
    discountedPrice: 4000,
    id: 39,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-women-half-slives-1.avif",
      ],
      previews: [
        "/images/products/gsp-women-half-slives-1.avif",
      ],
    },
  },
  {
    title: "Colored Mermaid",
    reviews: 10,
    price: 1000,
    discountedPrice: 1000,
    id: 40,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-colored-mermaid-1.avif",
        "/images/products/gsp-colored-mermaid-2.avif",
      ],
      previews: [
        "/images/products/gsp-colored-mermaid-1.avif",
        "/images/products/gsp-colored-mermaid-2.avif",
      ],
    },
  },
  {
    title: "Custom-made Green Emrald",
    reviews: 17,
    price: 4000,
    discountedPrice: 4000,
    id: 41,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-custom-made-green-emrald-1.avif",
      ],
      previews: [
        "/images/products/gsp-custom-made-green-emrald-1.avif",
      ],
    },
  },
  {
    title: "Dresses With a Classic",
    reviews: 24,
    price: 1000,
    discountedPrice: 1000,
    id: 42,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-dresses-with-a-classic-1.avif",
      ],
      previews: [
        "/images/products/gsp-dresses-with-a-classic-1.avif",
      ],
    },
  },
  {
    title: "Embellished With Beads",
    reviews: 6,
    price: 4000,
    discountedPrice: 4000,
    id: 43,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-embellished-with-beads-1.avif",
      ],
      previews: [
        "/images/products/gsp-embellished-with-beads-1.avif",
      ],
    },
  },
  {
    title: "Formal Chiffon Mermaid",
    reviews: 13,
    price: 1000,
    discountedPrice: 1000,
    id: 44,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-formal-chiffon-mermaid-1.avif",
      ],
      previews: [
        "/images/products/gsp-formal-chiffon-mermaid-1.avif",
      ],
    },
  },
  {
    title: "Green Halter-style",
    reviews: 20,
    price: 4000,
    discountedPrice: 4000,
    id: 45,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-green-halter-style-1.avif",
      ],
      previews: [
        "/images/products/gsp-green-halter-style-1.avif",
      ],
    },
  },
  {
    title: "Hooded Abaya With Special Work",
    reviews: 27,
    price: 1000,
    discountedPrice: 1000,
    id: 46,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-hooded-abaya-with-special-work-1.avif",
      ],
      previews: [
        "/images/products/gsp-hooded-abaya-with-special-work-1.avif",
      ],
    },
  },
  {
    title: "Party Abaya",
    reviews: 9,
    price: 1000,
    discountedPrice: 1000,
    id: 47,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-party-abaya-1.avif",
      ],
      previews: [
        "/images/products/gsp-party-abaya-1.avif",
      ],
    },
  },
  {
    title: "Pearl Polka Dot Print",
    reviews: 16,
    price: 4000,
    discountedPrice: 4000,
    id: 48,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-pearl-polka-dot-print-1.avif",
        "/images/products/gsp-pearl-polka-dot-print-2.avif",
        "/images/products/gsp-pearl-polka-dot-print-3.avif",
      ],
      previews: [
        "/images/products/gsp-pearl-polka-dot-print-1.avif",
        "/images/products/gsp-pearl-polka-dot-print-2.avif",
        "/images/products/gsp-pearl-polka-dot-print-3.avif",
      ],
    },
  },
  {
    title: "Shimmering Saudi Arabian Evening Dress",
    reviews: 23,
    price: 1000,
    discountedPrice: 1000,
    id: 49,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-shimmering-saudi-arabian-evening-dress-1.avif",
      ],
      previews: [
        "/images/products/gsp-shimmering-saudi-arabian-evening-dress-1.avif",
      ],
    },
  },
  {
    title: "Slim-fit Summer Party Dress",
    reviews: 5,
    price: 1000,
    discountedPrice: 1000,
    id: 50,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-slim-fit-summer-party-dress-1.avif",
      ],
      previews: [
        "/images/products/gsp-slim-fit-summer-party-dress-1.avif",
      ],
    },
  },
  {
    title: "Strapless Satin",
    reviews: 12,
    price: 4000,
    discountedPrice: 4000,
    id: 51,
    category: "Women's Tops & Sets",
    imgs: {
      thumbnails: [
        "/images/products/gsp-strapless-satin-1.avif",
      ],
      previews: [
        "/images/products/gsp-strapless-satin-1.avif",
      ],
    },
  },
  {
    title: "Summer Black Peplum",
    reviews: 19,
    price: 1000,
    discountedPrice: 1000,
    id: 52,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-summer-black-peplum-1.avif",
      ],
      previews: [
        "/images/products/gsp-summer-black-peplum-1.avif",
      ],
    },
  },
  {
    title: "Summer Peplum",
    reviews: 26,
    price: 1000,
    discountedPrice: 1000,
    id: 53,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-summer-peplum-1.avif",
      ],
      previews: [
        "/images/products/gsp-summer-peplum-1.avif",
      ],
    },
  },
  {
    title: "Two-piece Micro Bikini Swimsuit",
    reviews: 8,
    price: 1500,
    discountedPrice: 1500,
    id: 54,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-two-piece-micro-bikini-swimsuit-1.avif",
        "/images/products/gsp-two-piece-micro-bikini-swimsuit-2.avif",
      ],
      previews: [
        "/images/products/gsp-two-piece-micro-bikini-swimsuit-1.avif",
        "/images/products/gsp-two-piece-micro-bikini-swimsuit-2.avif",
      ],
    },
  },
  {
    title: "Vestidos Summer Dress",
    reviews: 15,
    price: 1000,
    discountedPrice: 1000,
    id: 55,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-vestidos-summer-dress-1.avif",
      ],
      previews: [
        "/images/products/gsp-vestidos-summer-dress-1.avif",
      ],
    },
  },
  {
    title: "White Mermaid-style",
    reviews: 22,
    price: 1000,
    discountedPrice: 1000,
    id: 56,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-white-mermaid-style-1.avif",
      ],
      previews: [
        "/images/products/gsp-white-mermaid-style-1.avif",
      ],
    },
  },
  {
    title: "Women's Small Swimsuit 2022",
    reviews: 29,
    price: 1500,
    discountedPrice: 1500,
    id: 57,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-women-s-small-swimsuit-2022-1.avif",
      ],
      previews: [
        "/images/products/gsp-women-s-small-swimsuit-2022-1.avif",
      ],
    },
  },
  {
    title: "Women's Small Swimsuit",
    reviews: 11,
    price: 1500,
    discountedPrice: 1500,
    id: 58,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-women-s-small-swimsuit-1.avif",
        "/images/products/gsp-women-s-small-swimsuit-2.avif",
      ],
      previews: [
        "/images/products/gsp-women-s-small-swimsuit-1.avif",
        "/images/products/gsp-women-s-small-swimsuit-2.avif",
      ],
    },
  },
  {
    title: "Women's Swimwear Fashion 2026",
    reviews: 18,
    price: 1500,
    discountedPrice: 1500,
    id: 59,
    category: "Swimwear",
    imgs: {
      thumbnails: [
        "/images/products/gsp-women-s-swimwear-fashion-2026-1.avif",
        "/images/products/gsp-women-s-swimwear-fashion-2026-2.avif",
        "/images/products/gsp-women-s-swimwear-fashion-2026-3.avif",
        "/images/products/gsp-women-s-swimwear-fashion-2026-4.avif",
      ],
      previews: [
        "/images/products/gsp-women-s-swimwear-fashion-2026-1.avif",
        "/images/products/gsp-women-s-swimwear-fashion-2026-2.avif",
        "/images/products/gsp-women-s-swimwear-fashion-2026-3.avif",
        "/images/products/gsp-women-s-swimwear-fashion-2026-4.avif",
      ],
    },
  },
  {
    title: "Achillea Womens Bp-025 Pashmina Shawl",
    reviews: 25,
    price: 6000,
    discountedPrice: 6000,
    id: 60,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-achillea-womens-bp-025-pashmina-shawl-1.jpg",
      ],
      previews: [
        "/images/products/gsp-achillea-womens-bp-025-pashmina-shawl-1.jpg",
      ],
    },
  },
  {
    title: "Cashmere Fringe Scarf",
    reviews: 7,
    price: 6000,
    discountedPrice: 6000,
    id: 61,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-cashmere-fringe-scarf-1.jpg",
      ],
      previews: [
        "/images/products/gsp-cashmere-fringe-scarf-1.jpg",
      ],
    },
  },
  {
    title: "Cashmere Womens Shawl Wrap",
    reviews: 14,
    price: 6000,
    discountedPrice: 6000,
    id: 62,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-cashmere-womens-shawl-wrap-1.jpg",
      ],
      previews: [
        "/images/products/gsp-cashmere-womens-shawl-wrap-1.jpg",
      ],
    },
  },
  {
    title: "Embroidery Shawl, Green Shawl",
    reviews: 21,
    price: 6000,
    discountedPrice: 6000,
    id: 63,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-embroidery-shawl-green-shawl-1.jpg",
      ],
      previews: [
        "/images/products/gsp-embroidery-shawl-green-shawl-1.jpg",
      ],
    },
  },
  {
    title: "Fine Wool Sozni Hand Embroidered Shawl, Stole",
    reviews: 28,
    price: 6000,
    discountedPrice: 6000,
    id: 64,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-fine-wool-sozni-hand-embroidered-shawl-stole-1.jpg",
      ],
      previews: [
        "/images/products/gsp-fine-wool-sozni-hand-embroidered-shawl-stole-1.jpg",
      ],
    },
  },
  {
    title: "Hdhdeueh Women's Solid Cashmere Scarf Knitted Long Shawl For Fall Winter",
    reviews: 10,
    price: 6000,
    discountedPrice: 6000,
    id: 65,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-hdhdeueh-women-s-solid-cashmere-scarf-knitted-lo-1.jpg",
      ],
      previews: [
        "/images/products/gsp-hdhdeueh-women-s-solid-cashmere-scarf-knitted-lo-1.jpg",
      ],
    },
  },
  {
    title: "Mitoku Scarf",
    reviews: 17,
    price: 6000,
    discountedPrice: 6000,
    id: 66,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-mitoku-scarf-1.jpg",
      ],
      previews: [
        "/images/products/gsp-mitoku-scarf-1.jpg",
      ],
    },
  },
  {
    title: "Pashmina Shawls Wraps Scarf",
    reviews: 24,
    price: 6000,
    discountedPrice: 6000,
    id: 67,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-pashmina-shawls-wraps-scarf-1.jpg",
      ],
      previews: [
        "/images/products/gsp-pashmina-shawls-wraps-scarf-1.jpg",
      ],
    },
  },
  {
    title: "Scarf Cashmere",
    reviews: 6,
    price: 6000,
    discountedPrice: 6000,
    id: 68,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-scarf-cashmere-1.jpg",
      ],
      previews: [
        "/images/products/gsp-scarf-cashmere-1.jpg",
      ],
    },
  },
  {
    title: "Scarf Mulberry Silk Hand Embroidery Shawls",
    reviews: 13,
    price: 6000,
    discountedPrice: 6000,
    id: 69,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-scarf-mulberry-silk-hand-embroidery-shawls-1.jpg",
      ],
      previews: [
        "/images/products/gsp-scarf-mulberry-silk-hand-embroidery-shawls-1.jpg",
      ],
    },
  },
  {
    title: "Scarf For Women American Mulberry Silk Scarf",
    reviews: 20,
    price: 6000,
    discountedPrice: 6000,
    id: 70,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-scarf-for-women-american-mulberry-silk-scarf-1.jpg",
      ],
      previews: [
        "/images/products/gsp-scarf-for-women-american-mulberry-silk-scarf-1.jpg",
      ],
    },
  },
  {
    title: "Scarf For Women Spring Summer Winter",
    reviews: 27,
    price: 6000,
    discountedPrice: 6000,
    id: 71,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-scarf-for-women-spring-summer-winter-1.jpg",
      ],
      previews: [
        "/images/products/gsp-scarf-for-women-spring-summer-winter-1.jpg",
      ],
    },
  },
  {
    title: "Shawl Wrap Pashmina Scarf Kashmiri Hand Made",
    reviews: 9,
    price: 6000,
    discountedPrice: 6000,
    id: 72,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-shawl-wrap-pashmina-scarf-kashmiri-hand-made-1.jpg",
      ],
      previews: [
        "/images/products/gsp-shawl-wrap-pashmina-scarf-kashmiri-hand-made-1.jpg",
      ],
    },
  },
  {
    title: "Shawl Wrap Pashmina Scarf",
    reviews: 16,
    price: 6000,
    discountedPrice: 6000,
    id: 73,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-shawl-wrap-pashmina-scarf-1.jpg",
      ],
      previews: [
        "/images/products/gsp-shawl-wrap-pashmina-scarf-1.jpg",
      ],
    },
  },
  {
    title: "Shawls Thick Warm",
    reviews: 23,
    price: 6000,
    discountedPrice: 6000,
    id: 74,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-shawls-thick-warm-1.jpg",
      ],
      previews: [
        "/images/products/gsp-shawls-thick-warm-1.jpg",
      ],
    },
  },
  {
    title: "Vintage Khatrast Butidar Pashmina",
    reviews: 5,
    price: 6000,
    discountedPrice: 6000,
    id: 75,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-vintage-khatrast-butidar-pashmina-1.jpg",
      ],
      previews: [
        "/images/products/gsp-vintage-khatrast-butidar-pashmina-1.jpg",
      ],
    },
  },
  {
    title: "Women Double-deck Mulberry Silk Hand Embroidery Flower Pattern",
    reviews: 12,
    price: 6000,
    discountedPrice: 6000,
    id: 76,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-women-double-deck-mulberry-silk-hand-embroidery--1.jpg",
      ],
      previews: [
        "/images/products/gsp-women-double-deck-mulberry-silk-hand-embroidery--1.jpg",
      ],
    },
  },
  {
    title: "Women Handwoven Pashmina Shawl",
    reviews: 19,
    price: 6000,
    discountedPrice: 6000,
    id: 77,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-women-handwoven-pashmina-shawl-1.jpg",
      ],
      previews: [
        "/images/products/gsp-women-handwoven-pashmina-shawl-1.jpg",
      ],
    },
  },
  {
    title: "Women's Evening Shawl Wrap Sheer Chiffon",
    reviews: 26,
    price: 1000,
    discountedPrice: 1000,
    id: 78,
    category: "Women's Dresses & Abayas",
    imgs: {
      thumbnails: [
        "/images/products/gsp-women-s-evening-shawl-wrap-sheer-chiffon-1.jpg",
      ],
      previews: [
        "/images/products/gsp-women-s-evening-shawl-wrap-sheer-chiffon-1.jpg",
      ],
    },
  },
  {
    title: "Women's Poncho Scarf",
    reviews: 8,
    price: 6000,
    discountedPrice: 6000,
    id: 79,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-women-s-poncho-scarf-1.jpg",
      ],
      previews: [
        "/images/products/gsp-women-s-poncho-scarf-1.jpg",
      ],
    },
  },
  {
    title: "Women's Winter Shawl Women's",
    reviews: 15,
    price: 6000,
    discountedPrice: 6000,
    id: 80,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-women-s-winter-shawl-women-s-1.jpg",
      ],
      previews: [
        "/images/products/gsp-women-s-winter-shawl-women-s-1.jpg",
      ],
    },
  },
  {
    title: "Womens Winter Scarf",
    reviews: 22,
    price: 6000,
    discountedPrice: 6000,
    id: 81,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-womens-winter-scarf-1.jpg",
      ],
      previews: [
        "/images/products/gsp-womens-winter-scarf-1.jpg",
      ],
    },
  },
  {
    title: "Wool Wrap For Women",
    reviews: 29,
    price: 6000,
    discountedPrice: 6000,
    id: 82,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-wool-wrap-for-women-1.jpg",
      ],
      previews: [
        "/images/products/gsp-wool-wrap-for-women-1.jpg",
      ],
    },
  },
  {
    title: "Wv-405 Shawl",
    reviews: 11,
    price: 6000,
    discountedPrice: 6000,
    id: 83,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-wv-405-shawl-1.jpg",
      ],
      previews: [
        "/images/products/gsp-wv-405-shawl-1.jpg",
      ],
    },
  },
  {
    title: "Ahanara Pashmina Vertical Stripes",
    reviews: 18,
    price: 6000,
    discountedPrice: 6000,
    id: 84,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-ahanara-pashmina-vertical-stripes-1.jpg",
      ],
      previews: [
        "/images/products/gsp-ahanara-pashmina-vertical-stripes-1.jpg",
      ],
    },
  },
  {
    title: "Deck Mulberry Silk Embroidery",
    reviews: 25,
    price: 6000,
    discountedPrice: 6000,
    id: 85,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-deck-mulberry-silk-embroidery-1.jpg",
      ],
      previews: [
        "/images/products/gsp-deck-mulberry-silk-embroidery-1.jpg",
      ],
    },
  },
  {
    title: "Mexa",
    reviews: 7,
    price: 6000,
    discountedPrice: 6000,
    id: 86,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-mexa-1.jpg",
      ],
      previews: [
        "/images/products/gsp-mexa-1.jpg",
      ],
    },
  },
  {
    title: "Ool Fabric Pashmina Kalamkari",
    reviews: 14,
    price: 6000,
    discountedPrice: 6000,
    id: 87,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-ool-fabric-pashmina-kalamkari-1.jpg",
      ],
      previews: [
        "/images/products/gsp-ool-fabric-pashmina-kalamkari-1.jpg",
      ],
    },
  },
  {
    title: "Womens Reversible Cashmere Shawl Duster",
    reviews: 21,
    price: 6000,
    discountedPrice: 6000,
    id: 88,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-womens-reversible-cashmere-shawl-duster-1.jpg",
      ],
      previews: [
        "/images/products/gsp-womens-reversible-cashmere-shawl-duster-1.jpg",
      ],
    },
  },
  {
    title: "Men's Shirt",
    reviews: 28,
    price: 2000,
    discountedPrice: 2000,
    id: 89,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-714fnhbmcbl-ac-sx679-1.jpg",
      ],
      previews: [
        "/images/products/gsp-714fnhbmcbl-ac-sx679-1.jpg",
      ],
    },
  },
  {
    title: "Men's Shirt",
    reviews: 10,
    price: 2000,
    discountedPrice: 2000,
    id: 90,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-71lwe-gtpsl-ac-sx679-1.jpg",
      ],
      previews: [
        "/images/products/gsp-71lwe-gtpsl-ac-sx679-1.jpg",
      ],
    },
  },
  {
    title: "Dry Shirts",
    reviews: 17,
    price: 2000,
    discountedPrice: 2000,
    id: 91,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-dry-shirts-1.jpg",
      ],
      previews: [
        "/images/products/gsp-dry-shirts-1.jpg",
      ],
    },
  },
  {
    title: "Long Sleeve Button up Shirt",
    reviews: 24,
    price: 2000,
    discountedPrice: 2000,
    id: 92,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-long-sleeve-button-up-shirt-1.jpg",
      ],
      previews: [
        "/images/products/gsp-long-sleeve-button-up-shirt-1.jpg",
      ],
    },
  },
  {
    title: "Loose Pocket Shirt",
    reviews: 6,
    price: 2000,
    discountedPrice: 2000,
    id: 93,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-loose-pocket-shirt-1.jpg",
      ],
      previews: [
        "/images/products/gsp-loose-pocket-shirt-1.jpg",
      ],
    },
  },
  {
    title: "Multi-pocket Motorcycle Jeans Men's",
    reviews: 13,
    price: 2000,
    discountedPrice: 2000,
    id: 94,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-multi-pocket-motorcycle-jeans-men-s-1.jpg",
      ],
      previews: [
        "/images/products/gsp-multi-pocket-motorcycle-jeans-men-s-1.jpg",
      ],
    },
  },
  {
    title: "Print Shirt",
    reviews: 20,
    price: 2000,
    discountedPrice: 2000,
    id: 95,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-print-shirt-1.jpg",
      ],
      previews: [
        "/images/products/gsp-print-shirt-1.jpg",
      ],
    },
  },
  {
    title: "Shirt Men Business Casual",
    reviews: 27,
    price: 2000,
    discountedPrice: 2000,
    id: 96,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-shirt-men-business-casual-1.jpg",
      ],
      previews: [
        "/images/products/gsp-shirt-men-business-casual-1.jpg",
      ],
    },
  },
  {
    title: "Shirt For Men",
    reviews: 9,
    price: 2000,
    discountedPrice: 2000,
    id: 97,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-shirt-for-men-1.jpg",
      ],
      previews: [
        "/images/products/gsp-shirt-for-men-1.jpg",
      ],
    },
  },
  {
    title: "Short Sleeve Crew",
    reviews: 16,
    price: 2000,
    discountedPrice: 2000,
    id: 98,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-short-sleeve-crew-1.jpg",
        "/images/products/gsp-short-sleeve-crew-2.jpg",
      ],
      previews: [
        "/images/products/gsp-short-sleeve-crew-1.jpg",
        "/images/products/gsp-short-sleeve-crew-2.jpg",
      ],
    },
  },
  {
    title: "Woolies Tech Long Sleeve",
    reviews: 23,
    price: 2000,
    discountedPrice: 2000,
    id: 99,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-woolies-tech-long-sleeve-1.jpg",
      ],
      previews: [
        "/images/products/gsp-woolies-tech-long-sleeve-1.jpg",
      ],
    },
  },
  {
    title: "Work Flat Front Shorts",
    reviews: 5,
    price: 2000,
    discountedPrice: 2000,
    id: 100,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-work-flat-front-shorts-1.jpg",
      ],
      previews: [
        "/images/products/gsp-work-flat-front-shorts-1.jpg",
      ],
    },
  },
  {
    title: "Summer Men's Fashion",
    reviews: 12,
    price: 2000,
    discountedPrice: 2000,
    id: 101,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-summer-men-s-fashion-1.avif",
        "/images/products/gsp-summer-men-s-fashion-2.avif",
      ],
      previews: [
        "/images/products/gsp-summer-men-s-fashion-1.avif",
        "/images/products/gsp-summer-men-s-fashion-2.avif",
      ],
    },
  },
  {
    title: "Two-piece Set Suitable For Casual",
    reviews: 19,
    price: 2000,
    discountedPrice: 2000,
    id: 102,
    category: "Men's Clothing",
    imgs: {
      thumbnails: [
        "/images/products/gsp-two-piece-set-suitable-for-casual-1.avif",
        "/images/products/gsp-two-piece-set-suitable-for-casual-2.avif",
      ],
      previews: [
        "/images/products/gsp-two-piece-set-suitable-for-casual-1.avif",
        "/images/products/gsp-two-piece-set-suitable-for-casual-2.avif",
      ],
    },
  },
  {
    title: "Beaming Incandescent",
    reviews: 26,
    price: 6000,
    discountedPrice: 6000,
    id: 103,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-beaming-incandescent-1.jpg",
      ],
      previews: [
        "/images/products/gsp-beaming-incandescent-1.jpg",
      ],
    },
  },
  {
    title: "Crimson Court",
    reviews: 8,
    price: 6000,
    discountedPrice: 6000,
    id: 104,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-crimson-court-1.jpg",
      ],
      previews: [
        "/images/products/gsp-crimson-court-1.jpg",
      ],
    },
  },
  {
    title: "Emerald Dream",
    reviews: 15,
    price: 6000,
    discountedPrice: 6000,
    id: 105,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-emerald-dream-1.jpg",
      ],
      previews: [
        "/images/products/gsp-emerald-dream-1.jpg",
      ],
    },
  },
  {
    title: "Festival Weave",
    reviews: 22,
    price: 6000,
    discountedPrice: 6000,
    id: 106,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-festival-weave-1.jpg",
      ],
      previews: [
        "/images/products/gsp-festival-weave-1.jpg",
      ],
    },
  },
  {
    title: "Giardino Segreto",
    reviews: 29,
    price: 6000,
    discountedPrice: 6000,
    id: 107,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-giardino-segreto-1.jpg",
        "/images/products/gsp-giardino-segreto-2.jpg",
      ],
      previews: [
        "/images/products/gsp-giardino-segreto-1.jpg",
        "/images/products/gsp-giardino-segreto-2.jpg",
      ],
    },
  },
  {
    title: "Pashmina Kalam Kari",
    reviews: 11,
    price: 6000,
    discountedPrice: 6000,
    id: 108,
    category: "Pashmina & Shawls",
    imgs: {
      thumbnails: [
        "/images/products/gsp-pashmina-kalam-kari-1.jpg",
      ],
      previews: [
        "/images/products/gsp-pashmina-kalam-kari-1.jpg",
      ],
    },
  },
];

export default shopData;
